<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertiesRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($criteria, $page = 1, $limit = 5)
    {
        $queryBuilder = $this->createQueryBuilder('p');

        if ($criteria['location']) {
            $queryBuilder
                ->leftJoin('p.fkLocation', 'l')
                ->where('l.locationName LIKE :location')
                ->setParameter('location', '%' . $criteria['location'] . '%');
        }

        if ($criteria['nearBeach']) {
            $queryBuilder
                ->AndWhere('p.nearBeach = :nearBeach')
                ->setParameter('nearBeach', 1);
        }

        if ($criteria['sleeps']) {
            $queryBuilder
                ->AndWhere('p.sleeps >= :sleeps')
                ->setParameter('sleeps', $criteria['sleeps']);
        }

        $queryBuilder
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return new Paginator($queryBuilder->getQuery());
    }
}
