AppBundle\Entity\Department:
    type: entity
    table: department
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: __pk
            generator:
                strategy: IDENTITY
    fields:
        departmentName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: department_name
    lifecycleCallbacks: {  }
