AppBundle\Entity\Employee:
    type: entity
    table: employee
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: __pk
            generator:
                strategy: IDENTITY
    fields:
        fkDepartment:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: _fk_department
        firstName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: last_name
        age:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
