AppBundle\Entity\Locations:
    type: entity
    table: locations
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: __pk
            generator:
                strategy: IDENTITY
    fields:
        locationName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: location_name
    lifecycleCallbacks: {  }
