AppBundle\Entity\Properties:
    type: entity
    repositoryClass: AppBundle\Repository\PropertiesRepository
    table: properties
    indexes:
        con-_fk_location-properties:
            columns:
                - _fk_location
    id:
        pk:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: __pk
            generator:
                strategy: IDENTITY
    fields:
        propertyName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: property_name
        nearBeach:
            type: boolean
            nullable: true
            column: near_beach
        acceptPets:
            type: boolean
            nullable: true
            column: accepet_pets
        sleeps:
            type: integer
            nullable: true
        beds:
            type: integer
            nullable: true
    manyToOne:
        fkLocation:
            targetEntity: Locations
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                _fk_location:
                    referencedColumnName: __pk
            orphanRemoval: false
    lifecycleCallbacks: {  }
